### ISSUE TITLE
Learn to add multiple issues to a milestone

### ISSUE THREAD

**Issue by yuppiecruncher** [yuppiecruncher/Dinsforbins#3]
- [x] make good use of the progress bar
- [x] add a third issue to see progress
- [x] complete a few issues to see more progress
